language: node_js

node_js:
  - "14"       
  - "13"       
  - "12"       
  - "10"       
  
env:
  global:
    - TIMEOUT_MULTIPLIER=8
  matrix:
    - SENECA_VER=seneca@3.x.x
    - SENECA_VER=seneca@plugin
    - SENECA_VER=senecajs/seneca

before_script:
  - npm uninstall seneca
  - npm install $SENECA_VER

after_script:
  - npm run coveralls
